# Generated by Django 5.0.4 on 2024-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('categories', models.CharField(choices=[('YAC', 'AC Room'), ('NAC', 'Non AC Room'), ('DEL', 'Deluxe Suite'), ('KIN', 'King Suite')], max_length=3)),
                ('no_of_beds', models.IntegerField()),
                ('room_capacity', models.IntegerField()),
            ],
        ),
    ]
