# Generated by Django 5.0.4 on 2024-04-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='categories',
            field=models.CharField(choices=[('YAC', 'AC Room'), ('NAC', 'Non AC Room'), ('DEL', 'Deluxe Suite'), ('KIN', 'King Suite'), ('QUE', 'Queen Suite'), ('NAU', 'Naukar Room')], max_length=3),
        ),
    ]
